export const GET_BID_REQUEST = "GET_BID_REQUEST";
export const GET_BID_SUCCESS = "GET_BID_SUCCESS";
export const GET_BID_FAILURE = "GET_BID_FAILURE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const YOUR_BID_REQUEST = "YOUR_BID_REQUEST";
export const YOUR_BID_SUCCESS = "YOUR_BID_SUCCESS";
export const YOUR_BID_FAILURE = "YOUR_BID_FAILURE";
